-- Generated by nwg-displays on 2026-08-23 at 20:48:39. Do not edit manually.

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@74.97",
    position = "3840x107",
    scale = 1.0
})
hl.monitor({
    output = "DP-2",
    mode = "1920x1080@240.06",
    position = "5760x107",
    scale = 1
})
