-- Generated by nwg-displays on 2026-08-23 at 20:48:33. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "DP-2",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "HDMI-A-1",
    default = true
})
hl.workspace_rule({
    workspace = "3",
    monitor = "HDMI-A-1"
})
hl.workspace_rule({
    workspace = "4",
    monitor = "HDMI-A-1"
})
hl.workspace_rule({
    workspace = "5",
    monitor = "DP-2"
})
